@R2	//GO TO FINAL ANSWER BOX
M=0	//ZERO ANS BOX

@R0
D=M
@END
D;JEQ	//IF ONE PRODUCT IS ZERO

@R1
D=M
@END
D;JEQ	//IF ONE PRODUCT IS ZERO

@R0	//NOT NECESSARY
D=M	//
@3	//
M=D	//ONLY TO KEEP THE NUMBERS BEING MUTLIPLED


(LOOP)
@R1	//GET 2ND NUM
D=M	//D HAS 2ND NUM

@R2	//GO TO FINAL ANSWER BOX
M=D+M	//RAM[2] NOW HAS 2ND NUMBER + ITS PREVIOUS VALUE

@R3	//GET 1ST NUM
M=M-1	//1ST NUM-1

D=M	//IDK WHY D NEEDS TO =M?
@LOOP	//WHERE TO JUMP TO
D;JGT	//JUMP		    (WHY CANT THIS BE M;JGT?)


(END)
@END
0;JMP	//FOREVER LOOP